// Options proposées sous forme de tuiles/chips dans l'onboarding — objectif :
// aucune saisie obligatoire. Chaque liste garde un échappatoire "+ Autre"
// pour les cas non couverts, géré par ChipMultiSelectWithCustom.

// Liste volontairement large (100+ secteurs) et triée par ordre alphabétique
// -- des retours utilisateurs montraient que le domaine recherché manquait
// souvent de la courte liste initiale (12 secteurs). Les 11 valeurs
// historiques (avant "Autre") sont conservées telles quelles : offer.sector
// et profile.sectors comparent des chaînes exactes, donc renommer une valeur
// existante casserait le matching des profils/offres déjà en base.
export const SECTORS = [
  "Achats",
  "Administration publique",
  "Aéronautique",
  "Agriculture",
  "Agroalimentaire",
  "Aide à domicile",
  "Ambulance et secours",
  "Animation",
  "Architecture",
  "Armée et défense",
  "Art",
  "Artisanat",
  "Assurance",
  "Audiovisuel",
  "Automobile",
  "Banque",
  "Beauté et esthétique",
  "Bibliothèque et documentation",
  "Bijouterie et joaillerie",
  "Biologie",
  "Biotechnologie",
  "Blockchain et Web3",
  "BTP",
  "Chimie",
  "Cinéma",
  "Coiffure",
  "Commerce",
  "Communication",
  "Comptabilité",
  "Conseil",
  "Culture",
  "Cybersécurité",
  "Data",
  "Décoration et ameublement",
  "Design",
  "Développement durable",
  "Diplomatie et international",
  "Distribution",
  "Douanes",
  "E-commerce",
  "Édition et livre",
  "Éducation et formation",
  "Électronique",
  "Énergie",
  "Enseignement",
  "Esport",
  "Événementiel",
  "Finance",
  "Fonction publique",
  "Franchise",
  "Gestion de projet",
  "Grande distribution",
  "Horlogerie",
  "Horticulture",
  "Hôtellerie",
  "Humanitaire et ONG",
  "Immobilier",
  "Import-export",
  "Industrie",
  "Informatique",
  "Ingénierie",
  "Intelligence artificielle",
  "Jeux vidéo",
  "Journalisme et presse",
  "Juridique et droit",
  "Kinésithérapie",
  "Logistique et transport",
  "Luxe",
  "Maintenance",
  "Marketing",
  "Mécanique",
  "Mode",
  "Musique",
  "Nettoyage et propreté",
  "Notariat",
  "Nutrition et diététique",
  "Optique",
  "Paysagisme",
  "Pêche",
  "Petite enfance",
  "Pharmacie",
  "Photographie",
  "Police et sécurité civile",
  "Politique",
  "Pompiers",
  "Produit",
  "Psychologie",
  "Publicité",
  "Qualité",
  "Radio",
  "Recherche scientifique",
  "Réseaux et télécoms",
  "Restauration",
  "Restauration collective",
  "RH",
  "Santé",
  "Sécurité",
  "Sécurité incendie",
  "Social et action sociale",
  "Sommellerie",
  "Sport",
  "Statistiques et actuariat",
  "Sylviculture et forêt",
  "Télévision",
  "Textile",
  "Tourisme",
  "Traduction et interprétariat",
  "Travail social",
  "Urbanisme",
  "Vente",
  "Vétérinaire",
  "Viticulture et œnologie",
  "Yoga et bien-être",
  "Autre",
];

export const SKILLS = [
  "JavaScript",
  "Python",
  "SQL",
  "React",
  "Excel avancé",
  "PowerPoint",
  "Photoshop",
  "Figma",
  "Canva",
  "SEO",
  "Google Ads",
  "Réseaux sociaux",
  "Rédaction",
  "Prospection",
  "Négociation",
  "Relation client",
  "CRM (Salesforce/HubSpot)",
  "Comptabilité",
  "Gestion budgétaire",
  "Gestion de projet",
  "Analyse de données",
  "Anglais courant",
  "Communication",
  "Organisation",
  "Travail d'équipe",
  "Créativité",
  "Autonomie",
  "Leadership",
];

export const TARGET_JOBS = [
  "Développeur web",
  "Data analyst",
  "Chef de projet",
  "Chargé de marketing digital",
  "Community manager",
  "UX/UI designer",
  "Commercial",
  "Assistant RH",
  "Chargé de communication",
  "Assistant comptable",
  "Growth hacker",
  "Technicien support",
  "Vendeur",
  "Assistant administratif",
  "Ingénieur DevOps",
];

export const TOP_CITIES = [
  "Paris",
  "Lyon",
  "Marseille",
  "Toulouse",
  "Bordeaux",
  "Lille",
  "Nantes",
  "Strasbourg",
  "Nice",
  "Rennes",
  "Montpellier",
  "Grenoble",
];

export const MOBILITY_OPTIONS = [
  { value: "Sur place uniquement", icon: "📍" },
  { value: "Mobile dans la région", icon: "🚗" },
  { value: "Mobile en France", icon: "🇫🇷" },
  { value: "Full remote", icon: "🏠" },
];

export const EDUCATION_LEVELS = ["Bac", "Bac+2", "Bac+3", "Bac+4", "Bac+5", "Bac+6 et plus"];

export const EXPERIENCE_LEVELS = [
  { value: "Aucune expérience", icon: "🌱" },
  { value: "Stage(s) réalisé(s)", icon: "🎓" },
  { value: "1-2 ans", icon: "💼" },
  { value: "3-5 ans", icon: "📈" },
  { value: "5 ans et plus", icon: "🏆" },
];

export type AvailabilityOption = { label: string; icon: string; daysFromNow: number | null };

export const AVAILABILITY_OPTIONS: AvailabilityOption[] = [
  { label: "Dès que possible", icon: "⚡", daysFromNow: 0 },
  { label: "Dans 1 mois", icon: "📅", daysFromNow: 30 },
  { label: "Dans 3 mois", icon: "🗓️", daysFromNow: 90 },
  { label: "Je ne sais pas encore", icon: "🤔", daysFromNow: null },
];
