// Options proposées sous forme de tuiles/chips dans l'onboarding — objectif :
// aucune saisie obligatoire. Chaque liste garde un échappatoire "+ Autre"
// pour les cas non couverts, géré par ChipMultiSelectWithCustom.

// Liste volontairement large (100+ secteurs) et triée par ordre alphabétique
// -- des retours utilisateurs montraient que le domaine recherché manquait
// souvent de la courte liste initiale (12 secteurs). Les 11 valeurs
// historiques (avant "Autre") sont conservées telles quelles : offer.sector
// et profile.sectors comparent des chaînes exactes, donc renommer une valeur
// existante casserait le matching des profils/offres déjà en base.
export const SECTORS = [
  "Achats",
  "Administration publique",
  "Aéronautique",
  "Agriculture",
  "Agroalimentaire",
  "Aide à domicile",
  "Ambulance et secours",
  "Animation",
  "Architecture",
  "Armée et défense",
  "Art",
  "Artisanat",
  "Assurance",
  "Audiovisuel",
  "Automobile",
  "Banque",
  "Beauté et esthétique",
  "Bibliothèque et documentation",
  "Bijouterie et joaillerie",
  "Biologie",
  "Biotechnologie",
  "Blockchain et Web3",
  "BTP",
  "Chimie",
  "Cinéma",
  "Coiffure",
  "Commerce",
  "Communication",
  "Comptabilité",
  "Conseil",
  "Culture",
  "Cybersécurité",
  "Data",
  "Décoration et ameublement",
  "Design",
  "Développement durable",
  "Diplomatie et international",
  "Distribution",
  "Douanes",
  "E-commerce",
  "Édition et livre",
  "Éducation et formation",
  "Électronique",
  "Énergie",
  "Enseignement",
  "Esport",
  "Événementiel",
  "Finance",
  "Fonction publique",
  "Franchise",
  "Gestion de projet",
  "Grande distribution",
  "Horlogerie",
  "Horticulture",
  "Hôtellerie",
  "Humanitaire et ONG",
  "Immobilier",
  "Import-export",
  "Industrie",
  "Informatique",
  "Ingénierie",
  "Intelligence artificielle",
  "Jeux vidéo",
  "Journalisme et presse",
  "Juridique et droit",
  "Kinésithérapie",
  "Logistique et transport",
  "Luxe",
  "Maintenance",
  "Marketing",
  "Mécanique",
  "Mode",
  "Musique",
  "Nettoyage et propreté",
  "Notariat",
  "Nutrition et diététique",
  "Optique",
  "Paysagisme",
  "Pêche",
  "Petite enfance",
  "Pharmacie",
  "Photographie",
  "Police et sécurité civile",
  "Politique",
  "Pompiers",
  "Produit",
  "Psychologie",
  "Publicité",
  "Qualité",
  "Radio",
  "Recherche scientifique",
  "Réseaux et télécoms",
  "Restauration",
  "Restauration collective",
  "RH",
  "Santé",
  "Sécurité",
  "Sécurité incendie",
  "Social et action sociale",
  "Sommellerie",
  "Sport",
  "Statistiques et actuariat",
  "Sylviculture et forêt",
  "Télévision",
  "Textile",
  "Tourisme",
  "Traduction et interprétariat",
  "Travail social",
  "Urbanisme",
  "Vente",
  "Vétérinaire",
  "Viticulture et œnologie",
  "Yoga et bien-être",
  "Autre",
];

export const SKILLS = [
  "JavaScript",
  "Python",
  "SQL",
  "React",
  "Excel avancé",
  "PowerPoint",
  "Photoshop",
  "Figma",
  "Canva",
  "SEO",
  "Google Ads",
  "Réseaux sociaux",
  "Rédaction",
  "Prospection",
  "Négociation",
  "Relation client",
  "CRM (Salesforce/HubSpot)",
  "Comptabilité",
  "Gestion budgétaire",
  "Gestion de projet",
  "Analyse de données",
  "Anglais courant",
  "Communication",
  "Organisation",
  "Travail d'équipe",
  "Créativité",
  "Autonomie",
  "Leadership",
];

export const TARGET_JOBS = [
  "Développeur web",
  "Data analyst",
  "Chef de projet",
  "Chargé de marketing digital",
  "Community manager",
  "UX/UI designer",
  "Commercial",
  "Assistant RH",
  "Chargé de communication",
  "Assistant comptable",
  "Growth hacker",
  "Technicien support",
  "Vendeur",
  "Assistant administratif",
  "Ingénieur DevOps",
];

export const TOP_CITIES = [
  "Paris",
  "Lyon",
  "Marseille",
  "Toulouse",
  "Bordeaux",
  "Lille",
  "Nantes",
  "Strasbourg",
  "Nice",
  "Rennes",
  "Montpellier",
  "Grenoble",
];

// Les 101 départements français (96 métropolitains + 5 d'outre-mer) --
// demande utilisateur : pouvoir chercher "tout un département" en plus
// d'une ville précise, pour les profils mobiles à l'échelle d'un
// département plutôt que d'une seule métropole. Saint-Pierre-et-Miquelon,
// Saint-Barthélemy et Saint-Martin sont des collectivités d'outre-mer, pas
// des départements, donc volontairement absents.
export const FRENCH_DEPARTMENTS: { code: string; name: string }[] = [
  { code: "01", name: "Ain" },
  { code: "02", name: "Aisne" },
  { code: "03", name: "Allier" },
  { code: "04", name: "Alpes-de-Haute-Provence" },
  { code: "05", name: "Hautes-Alpes" },
  { code: "06", name: "Alpes-Maritimes" },
  { code: "07", name: "Ardèche" },
  { code: "08", name: "Ardennes" },
  { code: "09", name: "Ariège" },
  { code: "10", name: "Aube" },
  { code: "11", name: "Aude" },
  { code: "12", name: "Aveyron" },
  { code: "13", name: "Bouches-du-Rhône" },
  { code: "14", name: "Calvados" },
  { code: "15", name: "Cantal" },
  { code: "16", name: "Charente" },
  { code: "17", name: "Charente-Maritime" },
  { code: "18", name: "Cher" },
  { code: "19", name: "Corrèze" },
  { code: "2A", name: "Corse-du-Sud" },
  { code: "2B", name: "Haute-Corse" },
  { code: "21", name: "Côte-d'Or" },
  { code: "22", name: "Côtes-d'Armor" },
  { code: "23", name: "Creuse" },
  { code: "24", name: "Dordogne" },
  { code: "25", name: "Doubs" },
  { code: "26", name: "Drôme" },
  { code: "27", name: "Eure" },
  { code: "28", name: "Eure-et-Loir" },
  { code: "29", name: "Finistère" },
  { code: "30", name: "Gard" },
  { code: "31", name: "Haute-Garonne" },
  { code: "32", name: "Gers" },
  { code: "33", name: "Gironde" },
  { code: "34", name: "Hérault" },
  { code: "35", name: "Ille-et-Vilaine" },
  { code: "36", name: "Indre" },
  { code: "37", name: "Indre-et-Loire" },
  { code: "38", name: "Isère" },
  { code: "39", name: "Jura" },
  { code: "40", name: "Landes" },
  { code: "41", name: "Loir-et-Cher" },
  { code: "42", name: "Loire" },
  { code: "43", name: "Haute-Loire" },
  { code: "44", name: "Loire-Atlantique" },
  { code: "45", name: "Loiret" },
  { code: "46", name: "Lot" },
  { code: "47", name: "Lot-et-Garonne" },
  { code: "48", name: "Lozère" },
  { code: "49", name: "Maine-et-Loire" },
  { code: "50", name: "Manche" },
  { code: "51", name: "Marne" },
  { code: "52", name: "Haute-Marne" },
  { code: "53", name: "Mayenne" },
  { code: "54", name: "Meurthe-et-Moselle" },
  { code: "55", name: "Meuse" },
  { code: "56", name: "Morbihan" },
  { code: "57", name: "Moselle" },
  { code: "58", name: "Nièvre" },
  { code: "59", name: "Nord" },
  { code: "60", name: "Oise" },
  { code: "61", name: "Orne" },
  { code: "62", name: "Pas-de-Calais" },
  { code: "63", name: "Puy-de-Dôme" },
  { code: "64", name: "Pyrénées-Atlantiques" },
  { code: "65", name: "Hautes-Pyrénées" },
  { code: "66", name: "Pyrénées-Orientales" },
  { code: "67", name: "Bas-Rhin" },
  { code: "68", name: "Haut-Rhin" },
  { code: "69", name: "Rhône" },
  { code: "70", name: "Haute-Saône" },
  { code: "71", name: "Saône-et-Loire" },
  { code: "72", name: "Sarthe" },
  { code: "73", name: "Savoie" },
  { code: "74", name: "Haute-Savoie" },
  { code: "75", name: "Paris" },
  { code: "76", name: "Seine-Maritime" },
  { code: "77", name: "Seine-et-Marne" },
  { code: "78", name: "Yvelines" },
  { code: "79", name: "Deux-Sèvres" },
  { code: "80", name: "Somme" },
  { code: "81", name: "Tarn" },
  { code: "82", name: "Tarn-et-Garonne" },
  { code: "83", name: "Var" },
  { code: "84", name: "Vaucluse" },
  { code: "85", name: "Vendée" },
  { code: "86", name: "Vienne" },
  { code: "87", name: "Haute-Vienne" },
  { code: "88", name: "Vosges" },
  { code: "89", name: "Yonne" },
  { code: "90", name: "Territoire de Belfort" },
  { code: "91", name: "Essonne" },
  { code: "92", name: "Hauts-de-Seine" },
  { code: "93", name: "Seine-Saint-Denis" },
  { code: "94", name: "Val-de-Marne" },
  { code: "95", name: "Val-d'Oise" },
  { code: "971", name: "Guadeloupe" },
  { code: "972", name: "Martinique" },
  { code: "973", name: "Guyane" },
  { code: "974", name: "La Réunion" },
  { code: "976", name: "Mayotte" },
];

function departmentLabel(dep: { code: string; name: string }): string {
  return `${dep.name} (${dep.code})`;
}

// Le 75 (Paris) est exclu ici : la ville "Paris" est déjà en tête de
// TOP_CITIES, un doublon "Paris" / "Paris (75)" dans la même liste ne
// ferait que semer la confusion au moment de choisir.
export const DEPARTMENT_LOCATIONS = FRENCH_DEPARTMENTS.filter((d) => d.code !== "75").map(
  departmentLabel,
);

// Liste combinée proposée dans le champ "Ta ville" de l'onboarding : les 12
// métropoles historiques en tête (affichées par défaut, comportement
// inchangé), puis tous les départements, atteignables via la recherche.
export const LOCATION_OPTIONS = [...TOP_CITIES, ...DEPARTMENT_LOCATIONS];

const DEPARTMENT_LOCATION_SET = new Set(DEPARTMENT_LOCATIONS);

// Utilisé par le matching (lib/matching/score.ts) pour reconnaître qu'un
// profil a choisi "tout un département" plutôt qu'une ville précise --
// dans ce cas une correspondance de sous-chaîne sur offer.location n'a pas
// de sens (le nom du département n'apparaît quasiment jamais dans une
// adresse d'offre).
export function isDepartmentLocation(city: string): boolean {
  return DEPARTMENT_LOCATION_SET.has(city);
}

export const MOBILITY_OPTIONS = [
  { value: "Sur place uniquement", icon: "📍" },
  { value: "Mobile dans la région", icon: "🚗" },
  { value: "Mobile en France", icon: "🇫🇷" },
  { value: "Full remote", icon: "🏠" },
];

export const EDUCATION_LEVELS = ["Bac", "Bac+2", "Bac+3", "Bac+4", "Bac+5", "Bac+6 et plus"];

export const EXPERIENCE_LEVELS = [
  { value: "Aucune expérience", icon: "🌱" },
  { value: "Stage(s) réalisé(s)", icon: "🎓" },
  { value: "1-2 ans", icon: "💼" },
  { value: "3-5 ans", icon: "📈" },
  { value: "5 ans et plus", icon: "🏆" },
];

export type AvailabilityOption = { label: string; icon: string; daysFromNow: number | null };

export const AVAILABILITY_OPTIONS: AvailabilityOption[] = [
  { label: "Dès que possible", icon: "⚡", daysFromNow: 0 },
  { label: "Dans 1 mois", icon: "📅", daysFromNow: 30 },
  { label: "Dans 3 mois", icon: "🗓️", daysFromNow: 90 },
  { label: "Je ne sais pas encore", icon: "🤔", daysFromNow: null },
];
